mysql:
  build: .
  dockerfile: Dockerfile-MySQL
  environment:
    MYSQL_ROOT_PASSWORD: root        #rootユーザ用のパスワード
    MYSQL_USER: user                 #作業ユーザ名
    MYSQL_PASSWORD: password         #作業ユーザ用のパスワード
    TZ: "Asia/Tokyo"
  ports:
    - 3306:3306
volumes:
    - ./db:/var/lib/mysql
